services:
    backend:
        build:
            context: .
            dockerfile: backend/Dockerfile
        container_name: jslt-backend
        environment:
            - PYTHONUNBUFFERED=1
        healthcheck:
            test:
                - CMD
                - curl
                - -f
                - http://localhost:8000/
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - dokploy-network

    frontend:
        build:
            context: ./frontend-v2
            dockerfile: Dockerfile.prod
            args:
                - VITE_API_URL=http://jslt-playground-dc1jon-4ed901-72-60-172-172.traefik.me
        container_name: jslt-frontend
        environment:
            - VITE_API_URL=http://jslt-playground-dc1jon-4ed901-72-60-172-172.traefik.me
        depends_on:
            - backend
        networks:
            - dokploy-network

networks:
    dokploy-network:
        external: true
